# Generated by Django 4.1.4 on 2023-01-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("full", models.CharField(max_length=500)),
                ("full_image", models.URLField()),
                ("half", models.CharField(max_length=500)),
                ("half_image", models.URLField()),
            ],
        ),
    ]
