# Generated by Django 4.1.4 on 2023-01-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measure", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="icon_type",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
