# Generated by Django 4.1.4 on 2022-12-30 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(max_length=2000)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('difficulty', models.IntegerField(default=3)),
                ('time_taken', models.CharField(max_length=20)),
                ('save_count', models.IntegerField(default=0)),
                ('theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme.theme')),
            ],
        ),
        migrations.CreateModel(
            name='RequiredIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=30)),
                ('substitute', models.CharField(max_length=50, null=True)),
                ('imoji', models.URLField(max_length=2000)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_ingredients', to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('short_desc', models.CharField(max_length=300)),
                ('long_desc', models.CharField(max_length=1000)),
                ('image', models.URLField(max_length=2000)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_sequence', to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=30)),
                ('substitute', models.CharField(max_length=50, null=True)),
                ('imoji', models.URLField(max_length=2000)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_ingredients', to='recipes.recipe')),
            ],
        ),
    ]
