# Generated by Django 4.1.4 on 2022-12-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_additionalingredients_additionalingredient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalingredient',
            name='imoji',
        ),
        migrations.RemoveField(
            model_name='requiredingredient',
            name='imoji',
        ),
        migrations.AddField(
            model_name='additionalingredient',
            name='emoji',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='requiredingredient',
            name='emoji',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
