# Generated by Django 4.1.4 on 2022-12-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_additionalingredient_emoji_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalingredient',
            name='substitute',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requiredingredient',
            name='substitute',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
