# Generated by Django 4.1.4 on 2023-01-03 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("theme", "0004_remove_theme_recipe_count"),
        ("recipes", "0006_alter_additionalingredient_substitute_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recipes",
                to="theme.theme",
            ),
        ),
    ]
