# Generated by Django 4.1.4 on 2023-01-03 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0007_alter_recipe_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="saved_user",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="saved_recipes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
