# Generated by Django 4.1.4 on 2023-01-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipe_saved_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.URLField(default='https://example.com', max_length=2000),
            preserve_default=False,
        ),
    ]
