# Generated by Django 4.1.4 on 2023-01-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0009_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe", name="video", field=models.CharField(max_length=2000),
        ),
    ]
