# Generated by Django 4.1.4 on 2023-01-21 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0010_alter_recipe_video"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe", old_name="video", new_name="video_id",
        ),
    ]
