# Generated by Django 4.1.4 on 2023-02-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_rename_video_recipe_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipesequence',
            name='time',
            field=models.CharField(default='3분', max_length=20),
            preserve_default=False,
        ),
    ]
