# Generated by Django 4.1.4 on 2022-12-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theme", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="saved_themes",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="saved_users", to="theme.theme"
            ),
        ),
    ]
