# Generated by Django 3.0.8 on 2022-12-28 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20221229_0123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='kakao_token',
        ),
    ]
