
# Generated by Django 4.1.4 on 2023-01-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_alter_additionalingredient_substitute_and_more"),
        ("user", "0002_alter_user_saved_themes"),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_recipes',
            field=models.ManyToManyField(blank=True, null=True, related_name='saved_users', to='recipes.recipe'),
        ),
    ]
