# Generated by Django 4.1.4 on 2023-01-03 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_saved_recipes"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="saved_recipes",),
        migrations.RemoveField(model_name="user", name="saved_themes",),
    ]
