# Generated by Django 4.1.4 on 2023-01-03 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("theme", "0002_alter_theme_theme_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theme",
            name="theme_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="themes",
                to="theme.themetype",
            ),
        ),
    ]
