# Generated by Django 4.1.4 on 2023-01-03 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theme", "0003_alter_theme_theme_type"),
    ]

    operations = [
        migrations.RemoveField(model_name="theme", name="recipe_count",),
    ]
