# Generated by Django 4.1.4 on 2023-01-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theme", "0004_remove_theme_recipe_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="recipe_count",
            field=models.IntegerField(default=0),
        ),
    ]
