# Generated by Django 4.1.4 on 2023-01-03 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("theme", "0005_theme_recipe_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme", name="save_count", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="theme",
            name="saved_user",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="saved_themes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
