# Generated by Django 4.1.4 on 2023-01-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theme", "0007_theme_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="long_image",
            field=models.URLField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
