# Generated by Django 4.1.4 on 2023-01-20 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theme", "0008_theme_long_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="theme", old_name="image", new_name="landscape_image",
        ),
        migrations.RenameField(
            model_name="theme", old_name="long_image", new_name="portrait_image",
        ),
    ]
